### ISSUE TITLE
Steps to Finalize S2S between Europa and Calypso

### ISSUE THREAD

**Issue by ebruoguzberk** [skalenetwork/metaport#1]
* High importance: Support Wrapped ETH (wETH but ERC20) in the IMA widget for Ruby to use in S2S so assets can be moved to Calypso with one transaction

* Develop a code that monitors the chain and sends the amount of Sfuel to the Calypso address. (when IMA sends a token detect event and SFUEL) This can be in this widget or an off-chain solution

**Comment by gannakulikova** [comment]
@dmitry-tk  to add Uniswap-like path

**Comment by gannakulikova** [comment]
this would take approx couple couple of days
