### ISSUE TITLE
[vite] Internal server error: Failed to resolve entry for package "@skalenetwork/metaport". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@skalenetwork/metaport". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by binhntfiber** [skalenetwork/metaport#104]
**Describe the bug**
Metaport cannot work with Vue3 + Vite2.9. When installed and call `new Metaport(options)`, it would throw the error below:

[vite] Internal server error: Failed to resolve entry for package "@skalenetwork/metaport". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@skalenetwork/metaport". The package may have incorrect main/module/exports specified in its package.json.

**To Reproduce**
1. Install Metaport package on project
2. Add a `div` with id = metaport
3. Call `new Metaport(options)`

**Expected behavior**
It should be work correctly
**Screenshots**
<img width="891" alt="Screenshot 2023-01-19 at 13 23 03" src="https://user-images.githubusercontent.com/98268645/213382741-2ad40cc6-d6a2-496b-88f7-a531e4fd2315.png">

**Desktop (please complete the following information):**

 - Browser: Chrome

**Comment by TheGreatAxios** [comment]
Follow Up Note from Original Filer:

```file package.json in metaport project https://github.com/skalenetwork/metaport/blob/develop/package.js`  line  "module": "build/index.esm.js",.  file index.esm.js cannot found when we install```

**Comment by jeffyzxc** [comment]
Also encountered this error: 

X [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "@skalenetwork/metaport". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@skalenetw
ork/metaport". The package may have incorrect main/module/exports specified in its package.json.


my package ss

dependencies
```JSON
    "vue": "^3.2.37",
    "vue-i18n": "^9.1.10",
    "vue-router": "^4.0.16",
    "vuex": "^4.0.2",
```

dev dependencies

```JSON
    "vite": "^2.9.12",
```

hope this helps
