### ISSUE TITLE
The requested module '/node_modules/@skalenetwork/metaport/build/index.js?v=6ffd250f' does not provide an export named 'Metaport'

### ISSUE THREAD

**Issue by binhntfiber** [skalenetwork/metaport#107]
**Describe the bug**
Metaport cannot work with Vue3 + Vite2.9. When installed and call new Metaport(options), it would throw the error below:
`Uncaught SyntaxError: The requested module '/node_modules/@skalenetwork/metaport/build/index.js?v=6ffd250f' does not provide an export named 'Metaport' (at App.vue:15:1)` on the console

**To Reproduce**
1.Install Metaport package on project
2.Add a div with id = metaport
3.Call new Metaport(options)
4.See error

**Expected behavior**
It should be work correctly

**Screenshots**
<img width="1364" alt="Screenshot 2023-01-30 at 10 09 40" src="https://user-images.githubusercontent.com/98268645/215420018-01cfe8a9-28c0-4188-a9bf-eafbf992e66a.png">

**Desktop (please complete the following information):**
Browser: Chrome

**Comment by TheGreatAxios** [comment]
- Attempted to reproduce with basic example: https://github.com/TheGreatAxios/vue-vite-metaport-bare-bones-setup
- Could not reproduce bug
