### ISSUE TITLE
Add mobile screen compatibility css classes

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/metaport#109]

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: 2.0.0-develop.7

Metaport was tested on mobile versions of Metamask and Coinbase. 



![Image](https://github.com/skalenetwork/metaport/assets/105824131/c6ff78bb-98b7-4807-b861-b228aaf22eb5)



![Image](https://github.com/skalenetwork/metaport/assets/105824131/a6fb7dbb-3be7-4616-abe6-ac9adf04c1f3)
