### ISSUE TITLE
This widget is not working on Next.js

### ISSUE THREAD

**Issue by hobbydev71** [skalenetwork/metaport#11]
I am getting the following error in Next.js project related to Metaport widget.
```
ReferenceError: document is not defined
```
https://github.com/skalenetwork/metaport/blob/develop/src/Metaport.tsx#L35
Next.js is Server Side Rendering, so `document` is `undefined`.
In my opinion it is better to create a new component instead of replacing `<div id="ima-widget">` in the real dom.

**Comment by dmytrotkk** [comment]
In our webpack build we have a browser-only configuration which results in multiple errors on the import stage, even before 

I’ve tested this approach and everything worked reasonably good: https://nextjs.org/docs/advanced-features/dynamic-import#with-external-libraries

Here’s a code sample that I’ve used to test:

```Javascript
// in react component

const [metaport, setMetaport] = React.useState();

  async function loadMetaport() {
    const Metaport = (await import('@skalenetwork/metaport')).Metaport;
    setMetaport(new Metaport({
      open: true,
      network: 'staging',
      schains: ['mainnet', 'rapping-zuben-elakrab'],
      tokens: {'mainnet': {'eth': {}}}
    }));
  }

  useEffect(() => {
    loadMetaport();
  }, []);

  useEffect(() => {
    if (metaport) {
      console.log('metaport widget initialized');
    }
  }, [metaport]);
```

@hobbydev71, if you have a better solution, please feel free to open a PR in this repo.

**Comment by hobbydev71** [comment]
This solution is working. Thanks @dmitry-tk.

**Comment by cstrangedk** [comment]
> This solution is working. Thanks @dmitry-tk.

Closing
