### ISSUE TITLE
[Bug] Metaport sometimes hangs when calling `.transfer()` from different button click events

### ISSUE THREAD

**Issue by thebrianbug** [skalenetwork/metaport#118]
**Describe the bug**

The `.transfer()` function of Metaport is currently very brittle. If you have only one call to `.transfer()` in your code, it usually works without issue. However, if you have multiple different configurations/transactions for `transfer()` on the same page of code, Metaport will frequently freeze on opening the widget, give an "unknown token key" error, and not load the rest of the widget. This can be mitigated by adding a call to `metaport.reset()` before calling `.transfer()`. This makes the widget work most of the time, but sometimes the error will still occur even still.

I've created a super simple app to demonstrate this issue [here](https://github.com/bmcilw1/example-metaport-app)

**To Reproduce**
1. Clone the [example repo](https://github.com/bmcilw1/example-metaport-app)
2. Install dependencies `npm install`
3. Run dev `npm run dev`
4. Connect a wallet (I've only tested with MetaMask)
5. Click a transfer button and use Metaport to complete the transfer
6. Click the other transfer button and interact with Metaport
7. Click the other button, repeat, and sometimes see error

If you do this many times, try clearing your cache, refreshing your browser, and try again. If you still can't reproduce then remove the calls to `metaport.reset()` before calling `.transfer()` and it should break most of the time.

**Expected behavior**

No matter how many button actions I hook up to different calls to `metaport.transfer()`...

- None of them should hang or give a unknown token error
- I should not need to call `.reset()` before calling `.transfer()`

**Screenshots**

![image](https://user-images.githubusercontent.com/1582095/220152086-a7f53179-22d2-4e47-81d7-1cdd56757bd8.png)

**Desktop (please complete the following information):**
 - OS: iOS 13.1
 - Browser: Chrome, Brave

**Comment by cstrangedk** [comment]
Resolved by #127
