### ISSUE TITLE
Add wrapper for transactions on a single chain

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/metaport#12]
We need a way to glue multiple transactions together to avoid multiple confirmations and simplify the UX of Metaport widget.

OpenZeppelin smart contract could be used, but it will require integration from each chain owner + additional configuration in Metaport. 

@payvint may help with Gnosis contracts.

We also need to modify UI to display 'path' of tokens.

**Comment by dmytrotkk** [comment]
need @payvint's help with multisend contract. moving to blocked.

cc: @gannakulikova @cstrangedk

**Comment by cstrangedk** [comment]
Closing as this is out-of-scope for metaport.  Will reopen under IMA spec
