### ISSUE TITLE
[Bug] ERC-721 TokenId is Undefined in _.transfer(...params) in 1.1.x

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/metaport#129]
**Describe the bug**
When calling metaport.transfer() and using the ERC-721 token standard, the UI widget shows **UNDEFINED** for the tokenId

**To Reproduce**
1. Setup Metaport using V1.1.x
2. Call metaport.transfer() -> ERC-721
3. UI will show UNDEFINED
4. Config found here: https://github.com/Dirt-Road-Development/skale-metaport-playground/pull/1

**Expected behavior**
Should show numerical value of tokenId and not undefined

**Screenshots**
<img width="463" alt="image" src="https://user-images.githubusercontent.com/20197130/222597746-9046fe53-da91-451b-add3-650ac3b35aa0.png">

**Comment by dmytrotkk** [comment]
ERC721 & ERC1155 support for transfer requests added in 1.2.0
