### ISSUE TITLE
Class name conflicts with other UI frameworks.

### ISSUE THREAD

**Issue by hobbydev71** [skalenetwork/metaport#13]
The 'hidden' class in the Metaport widget breaks some existing components with tailwindcss.

`hidden` class in this widget is defined as [here](https://github.com/skalenetwork/metaport/blob/develop/src/components/WidgetUI/Widget.scss#L409).
While tailwindcss's `hidden` class is defined as 
```
.hidden {
    display: none;
}
```
This makes some components of our projects hidden.
Is it possible to rename the class or make the class content the same as tailwindcss's?

 - OS: Windows
 - Browser: Chrome

**Comment by cstrangedk** [comment]
Closed, resolved for partner
