### ISSUE TITLE
Metaport main div overlapping content on height changes

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/metaport#134]
![image](https://user-images.githubusercontent.com/12778980/224444809-b45c60f1-194f-4d0d-a18b-226e935c2111.png)

**Comment by PolinaKiporenko** [comment]
to recheck

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Metaport Version - 2.0 develop

Now Metaport is scrollable, so there is no problem with overlapping 

https://github.com/skalenetwork/metaport/assets/105824131/929ab427-22b6-40c0-aa93-00dde9ac21e2
