### ISSUE TITLE
Add Token To Metamask - Exposed as function and availalbe in metaport.transfer(...config)

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/metaport#135]
**Is your feature request related to a problem? Please describe.**
This is not a direct problem, however, for users moving tokens to a new network for the first time; it can be confusing for them to not see the token in their wallet once the widget is done facilitating the transfer.

**Describe the solution you'd like**
It would be good to have a the **add to Metamask** work in two ways:

1) Available as a flag passed into Metaport.transfer() where you can pass in something like {...params, addToMetmask: true/false }. If true, then at the final destination add the token to the users wallet if it does not exist
2) Additionally, for dual use in Bridge UI and to be available as a function throughout a dApp; it could make sense to have addToMetamask(...config) available as an exposed function from the Metaport Object. 

It would then be usable via Bridge UI and solve https://github.com/skalenetwork/bridge-ui/issues/15 

Params would be in the form of https://docs.metamask.io/guide/registering-your-token.html#code-free-example

**Notes**
- This would help ease user onboarding 
- This would be a more flexible option than just issue 15 from Bridge UI

**Comment by yatsunastya** [comment]
Metaport Version: 2.0 develop

Now after completed transaction there appears a button "Add token" that enable users to add tokens to Metamask.


**Step 1.** After completed transaction click on "Add token" button in Metaport
![Image](https://github.com/skalenetwork/metaport/assets/105824131/12ac8a7f-5395-45cf-a7df-18d18a345e35)


**Step 2.** Click on "Add token" button in pop up Metamask window 
![Image](https://github.com/skalenetwork/metaport/assets/105824131/fd55a9cf-9d90-4c2d-b30c-460a8afac7a3)


**Step 3.** Check your added token in Metamask
![Image](https://github.com/skalenetwork/metaport/assets/105824131/87c1bec8-9406-4eca-a8d0-787dcf67a4ff)
