### ISSUE TITLE
Define and present multi-step process in metaport

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/metaport#14]
Currently the dapp-layer UI guides the user through a multi-step process (transfer + wrap...) however the widget is reloaded at each step to perform the action.
 
e.g.
1. Transfer ETH from Mainnet
2. Wrap and transfer to another chain
3. ...

How might the widget be populated with multiple steps, with a progress bar showing where the user is on the journey to complete the entire process.

**Comment by dmytrotkk** [comment]
part of the requested functionality will be implemented in https://github.com/skalenetwork/metaport/issues/102
