### ISSUE TITLE
Create metaport config generation UI

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/metaport#146]
OKR: Q2 2023

We need a tool to easily setup Metaport (token connections, chains, etc), so our dApps will be able to integrate Metaport to their website without our help. This can be done as a page on a Bridge website where dApp devs will be able to configure their Metaport setup.

Currently, we’re spending a considerable amount of time with each dApp that’s integrating our Metaport solution. This problem will be increasingly important once we will have more dApps on our platform.

**Comment by dmytrotkk** [comment]
can be started only after finishing all main 2.0.0 tickets
