### ISSUE TITLE
No message about faucet problem 

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/metaport#189]
**Describe the bug**
If there is no faucet on the chain and user is trying to get sFuel to their wallet, they don`t get any informative message about the error. 

https://github.com/skalenetwork/metaport/assets/105824131/da0180fb-0108-4f49-a3fa-4b26d2bdaeec

**Desktop (please complete the following information):**
 - OS:  macOS - 13.0.1
 - Browser: chrome - 114.0.5735.198
 - Metaport Version - 2.0 develop

**Comment by dmytrotkk** [comment]
New behavior:  if faucet is not available for source or destination chain, the following text will be displayed:
<img width="509" alt="Screenshot 2023-10-16 at 16 47 36" src="https://github.com/skalenetwork/metaport/assets/15244591/ad17733f-4e38-48c3-9547-d584d23fc928">

**Comment by dmytrotkk** [comment]
To reproduce:

Add any chain from the current network to the list of chains in the config (`src/metadata/metaportConfigStaging.ts`) after `mainnet` chain.

Also need to add your chain to `connections` section:

```
'chain-name': {},
...
```

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: 2.0.0-develop.3



![Image](https://github.com/skalenetwork/metaport/assets/105824131/a847291a-c0f9-4c9e-83a0-2f4f535bd5ea)
