### ISSUE TITLE
Add automated build/publish pipeline and standard versioning

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/metaport#19]
- Add automated build + publish pipeline on Github Actions 
- Use standard versioning system (same as for other SKALE JS libraries)

**Comment by dmytrotkk** [comment]
Build & publish pipeline added, also added test pipeline with a linter. 

Next step - add a full-fletched test pipeline with transfers.

**Comment by gannakulikova** [comment]
Done
