### ISSUE TITLE
Recharge Exit Gas Wallet transaction failed

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/metaport#190]
**Describe the bug**
In case user is trying to send less than 0.005 eth to exit gas wallet, transaction fails with no informative message in metaport

**To Reproduce**
1. Create S2M(Europa hub) transaction
2. Click on `Recharge Exit Gas Wallet`
3. Customise recharging amount to 0.001 and click on Recharge exit gas wallet
4. [Transaction](https://goerli.etherscan.io/tx/0x50477720a78fcbb9ea30a80936afed7aaa6f7014824b40b905cf093981db2179) fails and Metaport window is frozen for 2 min

**Screenshots**
<img width="456" alt="Знімок екрана 2023-10-04 о 16 40 58" src="https://github.com/skalenetwork/metaport/assets/105824131/45ac17fe-cab9-4b95-a3cb-af1ff4960002">

**Desktop (please complete the following information):**
 - OS:  macOS - 13.0.1
 - Browser: chrome - 114.0.5735.198
 - Metaport Version - 2.0 develop

**Comment by yatsunastya** [comment]
It's still possible to withdrow eth, even if there is 0 balance.  

<img width="445" alt="Знімок екрана 2023-10-09 о 15 50 34" src="https://github.com/skalenetwork/metaport/assets/105824131/381d44cb-667c-4e36-9c44-2af48dc62791">

**Comment by dmytrotkk** [comment]
Updated Community Pool logic: 

<img width="477" alt="Screenshot 2023-10-16 at 17 30 08" src="https://github.com/skalenetwork/metaport/assets/15244591/0a487db8-3699-43d4-adb9-3521bf474205">

<img width="489" alt="Screenshot 2023-10-16 at 17 42 18" src="https://github.com/skalenetwork/metaport/assets/15244591/5e220d90-92fb-4c1d-b391-f0877a229d4d">

**Comment by yatsunastya** [comment]
checked :white_check_mark: 
version: 2.0.0-develop.3

Now it's not possible to recharge exit gas wallet less than 0.005 eth and informative message is displayed. 
In case of 0 eth balance, there is no button "Withdraw all" 

![Image](https://github.com/skalenetwork/metaport/assets/105824131/0c695285-3ac8-4d7c-b443-c7419b107e48)

**Comment by yatsunastya** [comment]
But if no tokens exist on the chain, Exit Gas Wallet is still displayed. So it's necessary to remove it in such case. 

![Image](https://github.com/skalenetwork/metaport/assets/105824131/3ccdcad6-5497-42df-925d-a083b088e259)

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: 2.0.0-develop.6 

There is no Exit Gas Wallet for chains without tokens



![Image](https://github.com/skalenetwork/metaport/assets/105824131/29609429-c158-4a02-9712-64b55abb6b28)
