### ISSUE TITLE
Checking balance fails if number is small

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/metaport#192]
**Describe the bug**
In case of trying to transfer too small amount, checking balance fails

**Screens
<img width="956" alt="Знімок екрана 2023-10-04 о 18 18 23" src="https://github.com/skalenetwork/metaport/assets/105824131/fed63213-0b23-4ed4-b3a0-300f640c2aae">
hots**

**Desktop (please complete the following information):**
- OS: macOS - 13.0.1
- Browser: chrome - 114.0.5735.198
- Metaport Version - 2.0 develop

**Comment by dmytrotkk** [comment]
Handled small / incorrect amounts 
<img width="494" alt="Screenshot 2023-10-23 at 16 37 28" src="https://github.com/skalenetwork/metaport/assets/15244591/37e08266-1776-4682-ae59-787d135608c6">

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: 2.0.0-develop.4

Now "The amount is too small" message is shown 



![Image](https://github.com/skalenetwork/metaport/assets/105824131/6415b9fa-360c-4096-9300-62edbcee4574)
