### ISSUE TITLE
Balance is not displayed with small number

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/metaport#193]
**To Reproduce**
1. Transfer 0.000000000000001 of any token (for example)
2. Look at the balance - transferred amount is not displayed

**Screenshots**
<img width="428" alt="Знімок екрана 2023-10-04 о 18 38 16" src="https://github.com/skalenetwork/metaport/assets/105824131/4c7ab7e5-cbdb-4f04-909e-90ffb9e76729">

**Desktop (please complete the following information):**
- OS: macOS - 13.0.1
- Browser: chrome - 114.0.5735.198
- Metaport Version - 2.0 develop

**Comment by yatsunastya** [comment]
It's better to show the processed transfer at the `Transfer Completed` step or unable modifying tokens field (without clicking `start over`) 
<img width="431" alt="Знімок екрана 2023-10-09 о 13 40 27" src="https://github.com/skalenetwork/metaport/assets/105824131/95b7fc0e-624c-4029-ac0f-e08725ec908a">

**Comment by dmytrotkk** [comment]
Amount will be locked if transfer is in progress
<img width="473" alt="Screenshot 2023-10-23 at 20 25 18" src="https://github.com/skalenetwork/metaport/assets/15244591/972aa555-a393-4087-a96b-e575db7ac6a9">

**Comment by yatsunastya** [comment]
Version: 2.0.0-develop.4
The amount is really locked after the completed transfer. But balance still doesn't show small amount, even if it's possible to transfer it. 

![Image](https://github.com/skalenetwork/metaport/assets/105824131/1ec0f04d-1e85-4783-ae36-b3f0aa402200)

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [2.0.0-develop.6](https://github.com/skalenetwork/metaport/releases/tag/2.0.0-develop.6)

Balance is displayed even with minimum amount to transfer. 

![Image](https://github.com/skalenetwork/metaport/assets/105824131/8215c604-a548-4921-912d-e741c4b45a17)
