### ISSUE TITLE
Completed transactions are not displayed 

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/metaport#196]
**Describe the bug**
The transactions from history aren't displayed in wallet pop up window.

**Screenshots**
<img width="814" alt="Знімок екрана 2023-10-10 о 16 07 02" src="https://github.com/skalenetwork/metaport/assets/105824131/1da434bc-8fac-4b20-94bd-477987877d42">

**Desktop (please complete the following information):**
- OS: macOS - 13.0.1
- Browser: chrome - 114.0.5735.198
- Metaport Version - 2.0 develop

**Comment by dmytrotkk** [comment]
Fixed in develop.4

**Comment by dmytrotkk** [comment]
<img width="482" alt="Screenshot 2023-10-24 at 15 47 45" src="https://github.com/skalenetwork/metaport/assets/15244591/b3b292a4-a730-4371-82e1-748e8e9ac959">

**Comment by yatsunastya** [comment]
Chekced :white_check_mark: 
Version: 2.0.0-develop.4

Now all the transactions from the history are displayed in wallet popup window. 



![Image](https://github.com/skalenetwork/metaport/assets/105824131/36699690-4652-42cb-acdc-e29060c732c5)
