### ISSUE TITLE
Enkrypt wallet can't be connected

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/metaport#198]
**Describe the bug**
When Enkrypt wallet is downloaded and added to web browser, it is not possible to connect it to Metaport. 

**Screenshots**

https://github.com/skalenetwork/metaport/assets/105824131/02e0f35c-5197-4ad1-9846-c2edacda08a8

**Desktop (please complete the following information):**
- OS: macOS - 13.0.1
- Browser: Opera - 98.0.4759.39
- Metaport Version - 2.0 develop

**Comment by dmytrotkk** [comment]
Problems most probably caused by Storybook setup. 

Should work fine when opening in the new tab.
<img width="1048" alt="Screenshot 2023-10-24 at 20 09 14" src="https://github.com/skalenetwork/metaport/assets/15244591/8e901623-0657-4979-bf27-12623ff7d4ab">

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: 2.0.0-develop.6

It's possible to connect Enkrypt wallet to metaport outside of Storybook. 


https://github.com/skalenetwork/metaport/assets/105824131/e5acc14a-f890-4922-a120-f8fb3f5c5137
