### ISSUE TITLE
Wrong link for mainnet block explorer 

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/metaport#199]
**Describe the bug**
The wrong link is connected for mainnet block explorer. 

**To Reproduce**
1. Create M2S (Europa hub) eth transaction 
2. Click on 'Transfer'
3. Wait for completing the transaction
4. Check 'History' and find your trasaction 
5. Click on block explorer link and see an error

**Screenshots**

<img width="1417" alt="Знімок екрана 2023-10-16 о 12 55 44" src="https://github.com/skalenetwork/metaport/assets/105824131/a63363ea-23dd-4742-ab31-d09dfcd2eaf7">

**Desktop (please complete the following information):**
- OS: macOS - 13.0.1
- Browser: chrome - 114.0.5735.198
- Metaport Version - 2.0 develop

**Comment by dmytrotkk** [comment]
fixed by #208

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: 2.0.0-develop.6

Link is correct now. 



![Image](https://github.com/skalenetwork/metaport/assets/105824131/9d1bd4d5-1959-44cb-850f-1f9dd6485488)
