### ISSUE TITLE
sFUEL Station/sFUEL Integration

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/metaport#2]
## Overview
When you send funds from one chain to another you do not have sFUEL on the new chain.
In order to facilitate the automatic usage on another chain, thoughts on any of the following:

### Process/Idea

Pass a flag into the widget which is the dapp-chain-name for the dApp (this may already be there) and if the dApp supports sFUEL distribution. If the user is transferring from Europa currently (in the future with multi-hop, any chain) to the dApp chain and the dApp supports sFUEL distribution then nothing is needed. If the dApp does not support sFUEL distribution (may be common in smaller dApps on shared chains) then provide a link at the bottom of the widget that links to the sFUEL Station that was created from my understanding to solve this as a core piece for the multi-chain network.

### Reason

I sent funds from Europa -> Block Brawler, now I cannot send back without sFUEL. 

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20197130/178036094-3391b013-3870-439c-9517-e29aa4f70591.png">

**Comment by cstrangedk** [comment]
https://github.com/skalenetwork/IMA/issues/1221

**Comment by dmytrotkk** [comment]
For now going to add:

- sFuel icons for both chains
- Custom sFuel threshold for each chain
- Block transfer if there is no sFuel on the source chain
- Option for chains section in config - link to the custom sFuel station

**Comment by dmytrotkk** [comment]
@TheGreatAxios added sFuel integration support in [0.0.13-develop.1](https://www.npmjs.com/package/@skalenetwork/metaport/v/0.0.13-develop.1). 

Check out `minSfuelWei` and `faucetUrl` options in the docs. 

Please, confirm and close if everything works as expected.

![Image](https://user-images.githubusercontent.com/15244591/186717927-b6233b62-7968-4412-9311-a9da4ecf7f7f.png)

**Comment by TheGreatAxios** [comment]
@dmitry-tk Is the faucetURL field supposed to redirect to something like the sFUEL Station?

**Comment by TheGreatAxios** [comment]
Confirmed the value. Sounds like a great solution. Closing.
