### ISSUE TITLE
Additional UI features request.

### ISSUE THREAD

**Issue by hobbydev71** [skalenetwork/metaport#20]
1. Can I hide the Metaport icon normally and only show when specific action is triggered, ie `metaport.open()`?
![image](https://user-images.githubusercontent.com/81819318/184892810-7457ade7-cee0-4102-b541-b0a328fcb1aa.png)
![image](https://user-images.githubusercontent.com/81819318/184893681-d586a9c1-0cab-4d2a-9b66-2e432ddfe811.png)

2. Can I place the Metaport Widget on the bottom left instead of bottom right. If not can you add this option to Metaport widget configurations?

**Comment by dmytrotkk** [comment]
@hobbydev71 
Resolved in [0.0.13-develop.1](https://www.npmjs.com/package/@skalenetwork/metaport/v/0.0.13-develop.1), check out `openButton` option in the docs.

Please, confirm and close if everything works as expected.

**Comment by JasperGem** [comment]
> @hobbydev71 Resolved in [0.0.13-develop.1](https://www.npmjs.com/package/@skalenetwork/metaport/v/0.0.13-develop.1), check out `openButton` option in the docs.
> 
> Please, confirm and close if everything works as expected.

yeah, open works fine

**Comment by dmytrotkk** [comment]
thx, closing
