### ISSUE TITLE
Recharge Exit Gas Wallet doesn't work with Coinbase wallet

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/metaport#202]
**Describe the bug**
Exit Gas Wallet isn't activated after its recharging (Coinbase wallet)

**To Reproduce**
1. Create S2M transfer
2. Click on 'Recharge Exit Gas Wallet' and recharge it for default amount 0.005 eth
3. Wait for account activation
4. See that an account is not activated and still asking for recharging 

**Screenshots**
<img width="951" alt="Знімок екрана 2023-10-16 о 18 38 39" src="https://github.com/skalenetwork/metaport/assets/105824131/00ff62cd-4084-4369-bc3e-918ff8b1cb0f">

**Desktop (please complete the following information):**
- OS: macOS - 13.0.1
- Browser: Opera - 98.0.4759.39
- Metaport Version - 2.0 develop

**Comment by PolinaKiporenko** [comment]
Only in Coinbase, will be disabled initially , moved to Metaport 2.1

**Comment by PolinaKiporenko** [comment]
need to enable Coinbase and recheck on the new version
