### ISSUE TITLE
The page isn't unlocked after complete transfer

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/metaport#204]
**Describe the bug**
It is not reproducible each time. But still sometimes happens.
The metaport page is still locked after transaction was completed. 

**To Reproduce**
1. Complete S2S transfer 
2. See error

**Screenshots**
<img width="950" alt="Знімок екрана 2023-10-18 о 17 10 06" src="https://github.com/skalenetwork/metaport/assets/105824131/afb70b5e-112a-4672-9f2f-37bca0305700">

**Desktop (please complete the following information):**
- OS: macOS - 13.0.1
- Browser: chrome - 114.0.5735.198
- Metaport Version - 2.0 develop

**Comment by PolinaKiporenko** [comment]
Appears rarely, not critical, moved to Metaport 2.1 release
