### ISSUE TITLE
Transaction from schain crashes (Enkrypt)

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/metaport#210]
**Describe the bug**
Transaction completed, tokens are received on the destination chain but Enkrypt can't get transaction receipt, as a result metaport is stuck  

**To Reproduce**
1. Create transfer from Europa Hub to Mainnet
2. Click on "Transfer"
3. Wait - tokens are received on the destination chain, but metaport is stuck
4. See error in dev console  logs

**Screenshots**
<img width="939" alt="Знімок екрана 2023-10-25 о 13 19 45" src="https://github.com/skalenetwork/metaport/assets/105824131/dae70107-99c1-425e-abce-c4e4bf984f5c">

**Desktop (please complete the following information):**
- OS: macOS 14.0
- Browser: chrome 118.0.5993.88
- Metaport version: 2.0.0-develop.4

**Comment by PolinaKiporenko** [comment]
As temporary fix for Metaport 2.0 will disable wallets

**Comment by PolinaKiporenko** [comment]
need to enable Enkrypt and recheck on the new version

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.1.0-beta.3](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.3)

The issue is fixed

<img width="676" alt="Знімок екрана 2024-11-11 о 17 44 20" src="https://github.com/user-attachments/assets/c69d1697-610e-47a1-bd6e-f17be6c4249b">
