### ISSUE TITLE
Set gasprice during getRecommendedRechargeAmount

### ISSUE THREAD

**Issue by yavrsky** [skalenetwork/metaport#282]
In the IMA 2.3.0 we removed block.basefee from method getRecommendedRechargeAmount. It appears that block.basefee always returns 0 during eth_calls, so tx.gasprice was added instead. Now for getRecommendedRechargeAmount you need set gasprice to get reasonable value.

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.1.0-beta.2](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.2)

Recharge Exit Gas wallet [transaction](https://holesky.etherscan.io/tx/0x8380df9d394f294cb6aeaeaeb66d79e71023744a74504d1c5f5f3971d40ba49c)

<img width="589" alt="Знімок екрана 2024-11-04 о 15 24 57" src="https://github.com/user-attachments/assets/e4d6b64b-9dda-4caa-b444-37d05251bd99">

**Comment by EvgeniyZZ** [comment]
Additionally, this call required gasPric, as result this call will not work in block explorer, etherscan without additional changes.
