### ISSUE TITLE
Configurable Z-order in widget CSS

### ISSUE THREAD

**Issue by JasperGem** [skalenetwork/metaport#29]
`v0.0.13`

![image](https://user-images.githubusercontent.com/86413952/185950631-44f9e7e9-6e7b-4f4b-b24e-b2b2f2b181aa.png)

**Comment by dmytrotkk** [comment]
@JasperGem should be fixed in [0.0.13-develop.1](https://www.npmjs.com/package/@skalenetwork/metaport/v/0.0.13-develop.1), metaport popup now has z-index 9999.

Please, confirm and close if everything works.

**Comment by JasperGem** [comment]
9999 is fine but maybe you need to change to 9998 because of #45 anyway. Please document these numbers as we will also have to move our modal and popover to be compatible
