### ISSUE TITLE
UI/General Notes

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/metaport#3]
## Overview
The following are minor UI/UX notes that I took during an initial test phase.

### 1. Transaction Success - When the transfer is completed, it pops up a success notification in the bottom left of the screen which I need to double check, but I think is possibly part of the demo widget. A nice UX piece would possibly be to add a green success message right on the Metaport widget in order to show the user the success as their focus is on the widget. Additionally, if used on mobile and it is part of the demo widget it may be difficult to place/see that. The screenshot below shows the message in the bottom left after a completed transfer. 

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20197130/178036479-3a8b2686-e69c-4afd-9f9b-e80dc29885bb.png">

### 2. Number Underflow/Overflow (Min/Max) - User should not be able to type more than they have. User should also not be able to put a negative number. User should not be able to have 0 and show the transfer. 

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20197130/178037359-519a7cf9-276e-42a0-9c61-5e2e7b663e35.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20197130/178037319-70f07a75-a54b-4843-b802-fa8b1d2d6ce2.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20197130/178037281-38f0ed2d-d9a6-4f7a-9da3-fec684400b5e.png">

### 3. When approving an amount, if the user declines the wallet does not reset, even when closing the widget meaning they have to reload the entire application to reset the Metaport widget. 

https://user-images.githubusercontent.com/20197130/178039004-9d8ee10e-8827-45ff-bba4-0d37626de782.mov

### 4. Same as #3, when clicking Transfer, and then declining the transaction, the Metaport widget does not reset blocking the user from changing a value or continuing. 

https://user-images.githubusercontent.com/20197130/178039287-122b6709-0e4f-407e-9fea-6456134bae0c.mov

### 5. Canceling Transaction in the Widget - I don't think this is a big one, but it may be nice to provide the handler to cancel the transaction inside of the Metaport widget. Same as one of my notes above, once the widget is popped up it draws attention in meaning I did not notice the cancel button right away. Not an issue, just a note.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20197130/178039558-60d1e9a4-d8e7-4923-9450-cfc365f85286.png">

### 6. Chain/Token Management

When I click the switch button, but decline the switch in MetaMask i have achieved both of these results where I either have an empty token selection (image 1) or an infinite load bar (image 2). When I then manually switch networks in MetaMask it stays on infinite load which is the third image. Possible UX issue if user clicks the wrong chain on accident then the whole widget is blocked and the page must be restarted. 

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20197130/178039807-19bc3397-d547-4332-9fcf-416a9eeb2cb3.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20197130/178039937-cc6c0a75-5966-4079-8f13-f76a5979cda8.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20197130/178040144-49efe486-b387-4e04-9697-2a9c543ddc83.png">

Overall it looks amazing, and works well these are just the minor UI/UX issues I noticed.

**Comment by cstrangedk** [comment]
* 1 - this is defined in the dapp layer, not the metaport layer.  Can be customized / determined by the dapp developer.
* 2 - moved to #15
* 3 - #8 
* 4 - #8
* 5 - #8 
* 6 - #8

**Comment by cstrangedk** [comment]
Closing per migration to separate issues.
