### ISSUE TITLE
Token transfer paths are not the combination of all chains

### ISSUE THREAD

**Issue by JasperGem** [skalenetwork/metaport#30]
`v0.0.13` for the following configuration

![image](https://user-images.githubusercontent.com/86413952/185951563-63ae6510-6ae2-4517-8be3-247846fa6692.png)

it should not be possible (or it should be possible to prohibit) the transfers of the following

![image](https://user-images.githubusercontent.com/86413952/185951759-a86e0950-9158-46c4-b320-4fb03889c50b.png)

**Comment by dmytrotkk** [comment]
@JasperGem it's not possible to do this in advance, since token lookup starts only once both chains are selected. 

My proposal is to add `No tokens pairs for these 2 chains` text for this case.

Is it ok for you?

**Comment by JasperGem** [comment]
> @JasperGem it's not possible to do this in advance, since token lookup starts only once both chains are selected.
> 
> My proposal is to add `No tokens pairs for these 2 chains` text for this case.
> 
> Is it ok for you?

do you mean remove or style the 'Select Token' combo box differently? or put this message inside it. I would prefer if it was removed so that users did not try to click it

**Comment by dmytrotkk** [comment]
@JasperGem remove the combo box if there are no token pairs for selected chains

**Comment by dmytrotkk** [comment]
@JasperGem fixed in [0.1.1-develop.0](https://www.npmjs.com/package/@skalenetwork/metaport/v/0.1.1-develop.0)



![Image](https://user-images.githubusercontent.com/15244591/191583799-81324001-beea-4b8b-ba0f-7883022401a2.png)



Please, check it out and close the ticket.
