### ISSUE TITLE
Crash switching tx direction with unselected? token when MM switches network

### ISSUE THREAD

**Issue by JasperGem** [skalenetwork/metaport#31]
`v0.0.13`

![image](https://user-images.githubusercontent.com/86413952/185951990-61faaf8a-3dfa-4422-91a6-6345a52bb16a.png)

this occurs after connecting to the new network prompted by MM

**Comment by dmytrotkk** [comment]
@JasperGem could you please double-check if it's still reproducible on [0.0.13-develop.3](https://www.npmjs.com/package/@skalenetwork/metaport/v/0.0.13-develop.3) and add steps to reproduce if the problem persists.

**Comment by JasperGem** [comment]
> @JasperGem could you please double-check if it's still reproducible on [0.0.13-develop.3](https://www.npmjs.com/package/@skalenetwork/metaport/v/0.0.13-develop.3) and add steps to reproduce if the problem persists.

so we have not seen again this on `develop.3` but we do see other oddness which feels like #46

**Comment by JasperGem** [comment]
> @JasperGem could you please double-check if it's still reproducible on [0.0.13-develop.3](https://www.npmjs.com/package/@skalenetwork/metaport/v/0.0.13-develop.3) and add steps to reproduce if the problem persists.

actually cancel that - I have just seen it again on `develop.3`.

![image](https://user-images.githubusercontent.com/86413952/188988272-ff8f7ee3-91b8-4c0d-ab90-87bd44dc741e.png)
