### ISSUE TITLE
Document the recommended OZ wrapper SC (version) expected for `wraps` feature

### ISSUE THREAD

**Issue by JasperGem** [skalenetwork/metaport#32]
SSIA

Link in the readme would be enough

**Comment by dmytrotkk** [comment]
@JasperGem check out this README: https://github.com/skalenetwork/test-tokens#erc20-wrap-deploy

You can also find usage of these scripts here: https://github.com/skalenetwork/ima-js/blob/feature/move-to-ethers-js/scripts/deploy_s2s_tokens.sh

Feel free to close if that's enough.
