### ISSUE TITLE
Add url for configuring token icon

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/metaport#4]

**Comment by cstrangedk** [comment]
please add basic example to widget demo

**Comment by dmytrotkk** [comment]
@cstrangedk @hobbydev71 

Option for the custom icon is present in [0.0.13-develop.2](https://www.npmjs.com/package/@skalenetwork/metaport/v/0.0.13-develop.2).

Check out the `Token icons` section in the docs and sandbox section in the demo repo. 

Please, confirm and close if everything works as expected.

![Image](https://user-images.githubusercontent.com/15244591/186735762-c0e2f445-956b-4e3f-a760-2070630a184a.png)

**Comment by dmytrotkk** [comment]
@cstrangedk can we close this?
