### ISSUE TITLE
Can't get the metaport to start on React

### ISSUE THREAD

**Issue by GuillermoCAB** [skalenetwork/metaport#42]
**Describe the bug**
Try to initialize the metaport but get a lot of errors

**To Reproduce**
Install the lib
Add the `<div id='metaport'></div>` to the root page and tried to initialize it using:
```
import { Metaport } from '@skalenetwork/metaport';
const widget = new Metaport(METAPORT_OPTIONS);
```

**Expected behavior**
Should start metaport with no issues

**Screenshots**
![image (29)](https://user-images.githubusercontent.com/49039468/188011896-ba2bea72-f35f-4164-9e82-6d49c8cfcb48.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 105.0.5195.52

**Comment by dmytrotkk** [comment]
@GuillermoCAB which version of Metaport are you using?
Also - can you please send me your `METAPORT_OPTIONS`?

**Comment by GuillermoCAB** [comment]
@dmitry-tk 
Version: 0.0.13
METAPORT_OPTIONS : 
`{
    open: true, 
    openButton: false, 
    autoLookup: false, 
    theme: { 
        primary: '#00d4ff', 
        background: '#0a2540', 
        mode: 'dark' 
    }
}`

**Comment by dmytrotkk** [comment]
@GuillermoCAB can you please try with [0.0.13-develop.3](https://www.npmjs.com/package/@skalenetwork/metaport/v/0.0.13-develop.3) and confirm that problem still persists? 

You've added `<div id='metaport'></div>` to your `index.html`, right?

**Comment by TheGreatAxios** [comment]
Similar to #39. Must be added in the index.html as @dmitry-tk stated, however, it must be it's own div above the div id='root' from my last usage otherwise it will break the entire application.

**Comment by GuillermoCAB** [comment]
@dmitry-tk @TheGreatAxios Yeah I've added to the root but not outside the root div, so I did that, and solved the issue for me. Thanks so much for the help guys!
