### ISSUE TITLE
Add network check to the Metaport

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/metaport#46]
If the network is switched externally from Metamask, the widget will crash.

We need to add a listener that reacts to network change and blocks the widget if the network is not correct. 

This should also fix https://github.com/skalenetwork/metaport/issues/31

**Comment by JasperGem** [comment]
btw it seems like when it crashes in these circumstances It seems to reposition from bottom right to top left and re-show itself

**Comment by JasperGem** [comment]
> btw it seems like when it crashes in these circumstances It seems to reposition from bottom right to top left and re-show itself

![image](https://user-images.githubusercontent.com/86413952/188990998-ea7e3047-132b-4cc7-b593-f99fd097a2ae.png)
