### ISSUE TITLE
Add support for ERC721 and 1155 tokens

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/metaport#47]
We need to create an MVP for ERC721 token flow.

- Actions controlled from the outside (no items lookup)
- No visuals (no images for NFTs in the first version)

@cstrangedk Question: use ERC721 with metadata or the regular one?

**Comment by cstrangedk** [comment]
* Yes, actions controlled from the outside for MVP.  We'll reassess this for later versions
* No visuals, just use a boilerplate icon for the MVP

ERC721 with metadata, but can we also support the regular one?

**Comment by TheGreatAxios** [comment]
@cstrangedk 

If the Core interface of ERC721 with Metadata is IERC721 which is what ERC721 (default) inherits from then would it matter what the type is on the internals of the widget? Both support the same core transfer and balances functions. 

Additionally, If actions and data are passed in from an external source would it make sense to build a generic interface that has optional metadata with the defaults being address, type, contract name, token id, and balance (if 11155 standard).

Developers then would just pass in the NFT data directly that correlates to their project.

**Comment by cstrangedk** [comment]
quoting @TheGreatAxios 

> proposed alternative {for supporting erc721, erc721withmetadata, erc1155}

```{
   "chain-name": {
    "erc20": ...,
    "nfts": [
      {
        "name": "Name of NFT",
        "image": "uri here",
        "type": "ERC721", /// ERC721, ERC721Metadata, ERC1155
        //// Other details here ??
      }
    ]
   }
}```

**Comment by cstrangedk** [comment]
Merging from duplicate #36  @John-SKALE 

Widget Metaport NFT Support

- a simplified view that will display source and destination chain, ETH triangle 721/1155, nft name/family and token ID,
trigger transfer by outside application, buttons for each nft,

- Images from one chain to another - transfer will stay on 1 or move to 2 (fetch token contract, which contract address. Investigate but is it an option to see/pull all token IDs on contracts) need to discuss with D3 with block explorer/token ID to index or pull API,
- Pull and source of images (whom to handle it) ie store a link to an image? pull from URI

**Comment by dmytrotkk** [comment]
Resolved in https://github.com/skalenetwork/metaport/pull/67

@cstrangedk
