### ISSUE TITLE
Add flow for managing CommunityPool

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/metaport#6]
CommunityPool flow should be presented and designed, as an optional flow process set by the developer

**Comment by PolinaKiporenko** [comment]
@cstrangedk few suggestions for UI, for checking CommunityPool balance 

![Image](https://user-images.githubusercontent.com/101632617/187419038-19d0e86c-b48c-4567-a1a0-2b7abdd43efa.png)
![Image](https://user-images.githubusercontent.com/101632617/187419039-50630848-6dfe-4871-a838-1d2d675d5954.png)
