### ISSUE TITLE
Wallet unlock doesn't work for Metamask in Brave Browser

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/metaport#65]
When the wallet is locked, the 'Connect' button doesn't work in Brave Browser (it works correctly in Google Chrome)

<img width="398" alt="Screenshot 2022-10-07 at 12 01 06" src="https://user-images.githubusercontent.com/15244591/194538566-6d39f58f-5d35-492d-8dee-fe8b21f2533a.png">

**Comment by cstrangedk** [comment]
Not reproducible on Brave v1.48.164.
