### ISSUE TITLE
Approve Wrap checks wrapped token address instead of unwrapped token address

### ISSUE THREAD

**Issue by RubyAquaMarine** [skalenetwork/metaport#68]
**Describe the bug**
Metaport widget checks the ```balanceOf``` the wrapper token address instead of the unwrapped token address. Therefore, the user can not ```approve``` the wrapping of the unwrapped token aka ETHC.

**To Reproduce**
```metaport.config``` - 
```
 'WETH': { // wrapper token symbol 
          'address': '0x68eEAd7dc01Bfc822fa2005D4C8bF98C45cc7bB4', // wrapper token address
          'name': 'Wrapped ETH', // wrapper token display name
          'wraps': { // token that needs to be wrapped
            'address': '0xD2Aaa00700000000000000000000000000000000', // unwrapped token address
            'symbol': 'ETHC' // unwrapped token symbol
          }
        },
```

**Expected behavior**
Metaport widget should use the ```wraps.address``` within the metaport config for token approval (and checking ```balanceOf``` )

**Screenshots**

<img width="387" alt="Screen Shot 2022-10-25 at 7 36 27 PM" src="https://user-images.githubusercontent.com/86425604/197776103-4991cfff-9b01-43ef-ad3e-1f228a5d142a.png">

**Approval is skipped**

The "WRAP" button appears anyways and Metamask "Confirm" prompt appears to ```depositFor``` for a zero amount. 

**Chain details**
chainName: ```fancy-rasalhague```
ETHC : ```0xD2Aaa00700000000000000000000000000000000```
WETH: ```0x68eEAd7dc01Bfc822fa2005D4C8bF98C45cc7bB4``` - https://fancy-rasalhague.explorer.staging-v2.skalenodes.com/token/0x68eEAd7dc01Bfc822fa2005D4C8bF98C45cc7bB4/token-transfers

**Comment by dmitry-tk** [comment]
Resolved in https://github.com/skalenetwork/metaport/pull/67, new wrap+transfer flow described in https://github.com/skalenetwork/metaport/issues/72
