### ISSUE TITLE
Add single-chain actions to Metaport

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/metaport#7]
Add controlled actions for the widget:

- `widget.wrap(params)`
- `widget.unwrap(params)`
- `widget.transfer(params)` (rename `requestTransfer`)
- `widget.wrap_transfer(params)` (combined action)

We need a way to request partial actions (wrap/unwrap) without actual transfers.

**Comment by dmytrotkk** [comment]
need to restructure a bit to allow separate actions - will finish today

**Comment by dmytrotkk** [comment]
missing: one-chain actions (for example wrap-only)

**Comment by dmytrotkk** [comment]
One-chain actions are still missing. 
We need to discuss implementation details to have it in the widget.

2 actions need to be added first:

1. `wrap`
2. `unwrap`


CC @cstrangedk @gannakulikova @PolinaKiporenko

**Comment by cstrangedk** [comment]
Closing, wrap/unwrap methods not needed.  transfer and requestTransfer methods are complete
