### ISSUE TITLE
Modify flow for unwrapped and wrapped tokens

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/metaport#72]
- Remove unwrap/wrap paired balance display, and if unwrapped token display the balance of unwrapped. If a wrapped token is selected, display the balance of wrapped.
- As a user, I want to select a token and be presented with the steps/progress bar so I can understand how my action will proceed.
- As a user, I want to be able to differentiate between a wrapped token and  an unwrapped token in the token list.
- As a user, I want to select between wrapped and unwrapped tokens.
- As a user, I want to unwrap any wrapped token with a presented button with "Unwrap"

**Comment by dmytrotkk** [comment]
Suggested token flow for ERC20 S2S Wrap + Transfer:

<img width="1124" alt="Screenshot 2022-10-31 at 17 04 12" src="https://user-images.githubusercontent.com/15244591/199066536-cfbc0c64-6725-4a3a-8a3d-c43b0fb57462.png">

CC @cstrangedk

**Comment by dmytrotkk** [comment]
Regular ERC20 S2S flow for comparison:

<img width="776" alt="Screenshot 2022-10-31 at 17 04 20" src="https://user-images.githubusercontent.com/15244591/199066792-98e5d7b9-9809-4c27-a7dc-c2762a01437f.png">

**Comment by dmytrotkk** [comment]
@cstrangedk 

> Remove unwrap/wrap paired balance display. 

Which token balance should be shown for an unwrapped + wrapped token pair?

> As a user, I want to select a token and be presented with the steps/progress bar so I can understand how my action will proceed.

No changes here, we already have a stepper for that.

> As a user, I want to be able to differentiate between a wrapped token and an unwrapped token in the token list.

Now we have 2 options:

1. Set a pair of a wrapped + unwrapped token in the config and wrap+transfer as a single action
2. Set only wrapped token in the config and just transfer it 

We don't have `wrap` or `unwrap` actions in a widget right now.

Which tokens should be marked then?

> As a user, I want to select between wrapped and unwrapped tokens.

What does it mean?

> As a user, I want to unwrap any wrapped token.

Now we have the `transfer back + unwrap` action, but no `unwrap` action. 
You're suggesting adding it? Or I got it wrong?

**Comment by dmytrotkk** [comment]
Updated wrap+transfer token flow revised after discussion with @cstrangedk:

<img width="1062" alt="Screenshot 2022-11-01 at 16 52 29" src="https://user-images.githubusercontent.com/15244591/199290690-db9cd969-ffa7-49c3-b812-fd63fe6c2826.png">

**Comment by dmytrotkk** [comment]
An update regarding wrap/unwrap token flows:

1. Wrap process is implemented as described above (only the original token balance, symbol, and icon are shown, the wrap is the necessary step each time, etc)
2. Having wrapped tokens is considered an error state, except for the wrap+transfer operation 
3. If a user has wrapped tokens on a chain, a warning button will be displayed:
<img width="384" alt="Screenshot 2022-11-09 at 17 27 31" src="https://user-images.githubusercontent.com/15244591/200899228-228d1af0-e443-4198-b404-77fdaee72d06.png">

4. When clicked, a user will be redirected to the unwrap screen:
<img width="399" alt="Screenshot 2022-11-09 at 17 26 58" src="https://user-images.githubusercontent.com/15244591/200899135-8d7ce072-3f51-4cdc-b4ad-c17de9bab27e.png">

5. If a user is on a unwrap screen but there are no wrapped tokens left, the following screen will be displayed:

<img width="388" alt="Screenshot 2022-11-09 at 17 36 16" src="https://user-images.githubusercontent.com/15244591/200900954-b8a0046d-014f-4a62-b257-bc5c41c7ac66.png">

6. Changes related to the token naming: dApp developer will be able to specify the token name on the origin chain &  separate token name on a destination chain.


CC @gannakulikova @cstrangedk @John-SKALE @SKALE-jace

**Comment by cstrangedk** [comment]
@dmitry-tk re: 4, UI should also handle multiple wrapped wrapped tokens per @PolinaKiporenko mockups

**Comment by dmytrotkk** [comment]
@cstrangedk regarding this:

Token selection logic will be the same as for the regular transfer flows:

1. If there is only one wrapped token, it will be automatically selected and locked
2. If there are multiple wrapped tokens, the token selector will be displayed 

In 99% of such cases, users will have only 1 stuck token at the time so that it will be automatically pre-selected.
