### ISSUE TITLE
Metaport is broken after transferring back wrapped tokens

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/metaport#73]
**Describe the bug**

Metaport is broken after transferring back wrapped tokens and unwrapping them.

**To Reproduce**

0. Deploy and link wrapped token pair
1. Go to destination chain
2. Select the wrapped token
3. Click transfer, then unwrap
4. Confirm the network switch in Metamask
5. Wait for transfer and unwrap will be completed
6. Select another token and try transferring it - Metaport will crash:

<img width="1000" alt="Screenshot 2022-11-10 at 23 19 40" src="https://user-images.githubusercontent.com/15244591/201226961-1ac6ba78-e2b7-4de7-82ec-86b98e2f0234.png">

**Expected behavior**

The user should be able to transfer tokens again after the unwrap procedure.

**Additional context**

An error can be fixed by reloading the widget or switching chains.

**Comment by cstrangedk** [comment]
@dmytrotkk will double check and close if confirmed complete
