### ISSUE TITLE
Show current balance on user input

### ISSUE THREAD

**Issue by RubyAquaMarine** [skalenetwork/metaport#85]
Current balance is only displayed when the user enters a value larger than their balance. 
<img width="378" alt="Screen Shot 2022-11-17 at 8 50 12 PM" src="https://user-images.githubusercontent.com/86425604/202465319-85f58d6e-735f-473b-b5b4-ece630d211b1.png">

**Describe the solution you'd like**
A - Current balance is displayed when user interacts with amount_box
B - Current balance is displayed when user has entered x.xxxx (forth digit after decimal)
C - Current balance is shown if user wallet contains a value beyond x.xxxx

**Describe alternatives you've considered**
remove `current balance` text completely and show the correct value from user's wallet (correct decimal precision) within the original amount field next to $symbol 
<img width="380" alt="Screen Shot 2022-11-17 at 8 49 41 PM" src="https://user-images.githubusercontent.com/86425604/202467084-124b57df-1a4a-4974-aa0e-5a3afab8fca6.png">

**Comment by RubyAquaMarine** [comment]
can you also add a  ``decimal_limiter`` for the ``user_input_amount`` box. therefore users aren't propped with this error. 
<img width="335" alt="Screen Shot 2022-11-18 at 4 30 56 PM" src="https://user-images.githubusercontent.com/86425604/202668889-ca47e20d-d02f-467d-92ae-0823bfd2e134.png">

**Comment by PolinaKiporenko** [comment]
done
