### ISSUE TITLE
Widget closes after network switching 

### ISSUE THREAD

**Issue by RubyAquaMarine** [skalenetwork/metaport#90]
**Describe the bug**
Let's say you go to [ruby.exchange](http://ruby.exchange/) while connected to a non-supported network (which many people will)
you open MetaPort and select Calypso Hub. Once you've switched chains within Metamask, Metaport widget closes. You have to reopen it to proceed.

**To Reproduce**
1. connected to a non-supported network  [ruby.exchange](http://ruby.exchange/) 
2. open MP and select Calypso Hub
3. switch network within metamask
4. watch widget disappear

**Expected behavior**
Widget should stay open while switching from an unsupported network within metamask

 - Version 1.0.0-develop.4

**Comment by dmitry-tk** [comment]
@RubyAquaMarine 
Actually, Ruby's code closes the widget when the network is switched, not ours.
I've tried it on https://ruby.exchange/ and I see the following log:
```
metaport:Widget closeWidget event processed +529ms
```
which means `metaport.close()` was executed on your side.
