### ISSUE TITLE
User Onboarding & Flows

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/metaport#99]
**Is your feature request related to a problem? Please describe.**
Yes, as more networks are adding, Metaport can quickly and efficiently be expanded to support the networks on the technical front. 
On the user front, it requires some level of technical understanding to use Metaport i.e where to start, where to go, what token to send depending on the dApp/project/chain you are trying to use.

**Describe the solution you'd like**
How to simplify this using additional UI as opposed to adding more complexity to the logic directly.

1) An optional modal addition to Metaport
2) The modal would be center screen and have >z-index than all other components
3) Takes JSX/TSX children as parameters meaning Metaport functionality can be passed in
4) Ability to create walkthroughs or user flows using React Elements
5) Users can read and/or follow along

This should help dApps on chains utilizing the IMA bridge to onboard users in a more deterministic manner

**Describe alternatives you've considered**
- External solutions such as blogs, landing pages, etc

**Additional context**
- Could also utilize prompts to get user values and automate the whole process i.e bridge L1 -> Calypso (via Europa) with all the functions auto passed in with wrapping

**Comment by PolinaKiporenko** [comment]
@TheGreatAxios will be resolved in 2.0.0 version, please review

**Comment by yatsunastya** [comment]
No QA status
